[default.extend-words]
EIN = "EIN"
ba = "ba"

[files]
extend-exclude = [
    "website/public/install_roc.ps1",
    "website/public/install_roc.sh",
    "website/public/fzstd.mjs",
    ".github/workflows/CI.yml",
]
